### ISSUE TITLE
Change the Title and favicon of this Site

### ISSUE THREAD

**Issue by sujayx07** [DevSapta27/GDG-ON-CAMPUS#1]
🤔🤔🤔🤔

**Comment by DevSapta27** [comment]
U are welcomed to contribute in my Project
Go through the readme.md and contribution.md 
If you want any help , feel free to contact me through my Email

**Comment by DevSapta27** [comment]
Good work @SujayDeyTMSL !!

**Comment by DevSapta27** [comment]
I am closing this Issue as the problem has been solved by @SujayDeyTMSL !!
